apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fq3ynmqiw-go 
  janus-idp.io/tekton: fq3ynmqiw-go
  backstage.io/kubernetes-id: fq3ynmqiw-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fq3ynmqiw-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml