apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fq3ynmqiw-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fq3ynmqiw-go 
  name: fq3ynmqiw-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fq3ynmqiw-go 
